### ISSUE TITLE
Search in issues of a specific repository

### ISSUE THREAD

**Issue by marufsiddiqui** [rwieruch/react-graphql-github-apollo#15]
Hi all,

First of all, this is a great repo that helped me with getting started with React, Apollo, and GraphQl.

Probably its more of a GitHub GraphQL API related question. Based on this repo, I'm trying to create a demo app that will allow the user to search issues of a specific repository. I was able to list issues of a specific repository. But I couldn't find information on how to search issues of a specific repository. There's a top level search option but it gets results from all repositories.

It'd be very helpful if anyone can give me some clue

**Comment by rwieruch** [comment]
It boils down to GitHub's GraphQL API. I found the top level repository search as well, but cannot remember anything related to searching issues. I was looking for a follow mutation once, but seems like they don't offer it (yet).

**Comment by marufsiddiqui** [comment]
@rwieruch thanks for your quick reply. I'll try asking in GitHub Platform Community

**Comment by rwieruch** [comment]
If you get any insights on this topic, maybe you come back to give a brief note about it here :)

**Comment by marufsiddiqui** [comment]
@rwieruch I posed the question in GitHub Platform Community at https://platform.github.community/t/search-in-issues-of-a-specific-repository-using-github-api-v4/5853 and @rlinehan gave a solution. I'm yet to try it out though

**Comment by rwieruch** [comment]
Oh wow. You can be flexible about the type you are searching for. That's great!
