### ISSUE TITLE
Add Prettier

### ISSUE THREAD

**Issue by rwieruch** [rwieruch/react-graphql-github-apollo#7]
It would be great to follow a unified code style in the repository for people contributing to it. That's why I would propose [Prettier](https://github.com/prettier/prettier) for it. Even though everyone has to install it on their own, there are a couple of things that would help people to get started.

- [x] add a [Prettier configuration file](https://prettier.io/docs/en/configuration.html) to the project (e.g. with dangling comma true, semicolons true)

- [x] add a "prettier" script to the scripts *package.json* block to format all files via the command line. This can be done one time initially to have a unified code style. 

- [x] add a Contribution section at the bottom of the README.md mentioning to install a Prettier editor/IDE integration (e.g. [VS Code](https://github.com/prettier/prettier-vscode)) and to enforce it on save file (e.g. [VS Code](https://github.com/prettier/prettier-vscode#format-on-save)).

**Comment by M-ZubairAhmed** [comment]
Can I take this issue

**Comment by rwieruch** [comment]
@M-ZubairAhmed Sure! Looking forward to it!

**Comment by M-ZubairAhmed** [comment]
@rwieruch i have added prettier will process to adding the contribution section soon. I have added much config just what you have mentioned in the isse. Also i have run the command since that will make this pr huge.

**Comment by rwieruch** [comment]
Closed thanks to @M-ZubairAhmed ❤️
